# Generated by Django 4.2.7 on 2026-08-19 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parcelles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('alerte', '🔴 Alerte'), ('info', '🟢 Information'), ('rappel', '🟡 Rappel'), ('ia', '🧠 IA'), ('meteo', '🌤 Météo')], default='info', max_length=20)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('lien', models.CharField(blank=True, help_text='Lien vers la page concernée', max_length=200)),
                ('lue', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('agriculteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('parcelle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='parcelles.parcelle')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_creation'],
            },
        ),
    ]
