# Generated by Django 4.2.7 on 2026-08-19 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cultures', '0001_initial'),
        ('parcelles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegleAgronomique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conditions', models.JSONField(help_text='Ex: {"pluie": ">20", "jours_sans_pluie": ">7", "temp_max": ">35", "retard": ">5"}')),
                ('conseil', models.TextField(help_text='Message de recommandation')),
                ('solution', models.TextField(blank=True, help_text="Solution recommandée pour l'agriculteur")),
                ('source', models.CharField(choices=[('meteo', 'Météo'), ('calendrier', 'Calendrier'), ('regle', 'Règle agronomique'), ('retard', 'Retard')], default='regle', max_length=20)),
                ('niveau', models.CharField(choices=[('critique', '🔴 Critique'), ('important', '🟠 Important'), ('conseil', '🟢 Conseil')], default='conseil', max_length=20)),
                ('priorite', models.IntegerField(default=2, help_text='1=Haute, 2=Moyenne, 3=Basse')),
                ('active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regles', to='cultures.culture')),
                ('etape', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regles', to='cultures.etapeculturelle')),
            ],
            options={
                'verbose_name': 'Règle agronomique',
                'verbose_name_plural': 'Règles agronomiques',
                'ordering': ['priorite', '-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Recommandation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, help_text='Titre de la recommandation', max_length=200)),
                ('message', models.TextField(help_text='Message détaillé')),
                ('solution', models.TextField(blank=True, help_text='Solution proposée')),
                ('niveau', models.CharField(choices=[('critique', '🔴 Critique'), ('important', '🟠 Important'), ('conseil', '🟢 Conseil')], max_length=20)),
                ('source', models.CharField(choices=[('meteo', 'Météo'), ('calendrier', 'Calendrier'), ('regle', 'Règle agronomique'), ('retard', 'Retard')], max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('lue', models.BooleanField(default=False, help_text="L'utilisateur a-t-il lu cette recommandation ?")),
                ('appliquee', models.BooleanField(default=False, help_text="L'utilisateur a-t-il appliqué cette recommandation ?")),
                ('active', models.BooleanField(default=True, help_text='La recommandation est-elle toujours active ?')),
                ('contexte', models.JSONField(blank=True, default=dict, help_text='Contexte au moment de la génération (météo, âge, statut, etc.)')),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommandations', to='parcelles.parcelle')),
                ('regle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recommandations.regleagronomique')),
            ],
            options={
                'verbose_name': 'Recommandation',
                'verbose_name_plural': 'Recommandations',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueRecommandation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champ', models.CharField(max_length=50)),
                ('ancienne_valeur', models.JSONField(blank=True, null=True)),
                ('nouvelle_valeur', models.JSONField(blank=True, null=True)),
                ('date_modification', models.DateTimeField(auto_now_add=True)),
                ('recommandation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='recommandations.recommandation')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique recommandation',
                'verbose_name_plural': 'Historiques recommandations',
                'ordering': ['-date_modification'],
            },
        ),
    ]
