# Generated by Django 4.2.7 on 2026-08-19 10:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('cereale', 'Céréale'), ('tubercule', 'Tubercule'), ('legumineuse', 'Légumineuse'), ('maraicher', 'Maraîcher'), ('oleagineux', 'Oléagineux')], max_length=20)),
                ('nom_scientifique', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('emoji', models.CharField(default='🌱', max_length=10)),
                ('duree_min', models.PositiveIntegerField(help_text='Durée minimale du cycle en jours')),
                ('duree_max', models.PositiveIntegerField(help_text='Durée maximale du cycle en jours')),
                ('temperature_min', models.FloatField(default=10, help_text='Température minimale °C')),
                ('temperature_optimum', models.FloatField(default=25, help_text='Température optimale °C')),
                ('temperature_max', models.FloatField(default=35, help_text='Température maximale °C')),
                ('besoin_eau_min', models.FloatField(default=300, help_text='Besoins en eau minimum en mm/cycle', validators=[django.core.validators.MinValueValidator(0)])),
                ('besoin_eau_max', models.FloatField(default=800, help_text='Besoins en eau maximum en mm/cycle', validators=[django.core.validators.MinValueValidator(0)])),
                ('tolerance_exces_eau', models.IntegerField(choices=[(1, 'Faible'), (2, 'Moyenne'), (3, 'Élevée')], default=2)),
                ('tolerance_secheresse', models.IntegerField(choices=[(1, 'Faible'), (2, 'Moyenne'), (3, 'Élevée')], default=2)),
                ('active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Culture',
                'verbose_name_plural': 'Cultures',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='SourceAgronomique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('organisation', models.CharField(max_length=200)),
                ('auteur', models.CharField(blank=True, max_length=200)),
                ('annee', models.IntegerField()),
                ('url', models.URLField(blank=True)),
                ('date_consultation', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Source agronomique',
                'verbose_name_plural': 'Sources agronomiques',
                'ordering': ['-annee'],
            },
        ),
        migrations.CreateModel(
            name='ZoneAgricole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('territoire', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Zone agricole',
                'verbose_name_plural': 'Zones agricoles',
                'ordering': ['province', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='ProfilClimatique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_min', models.FloatField(help_text='Température minimale °C')),
                ('temp_opt_min', models.FloatField(help_text='Température optimale minimale °C')),
                ('temp_opt_max', models.FloatField(help_text='Température optimale maximale °C')),
                ('temp_max', models.FloatField(help_text='Température maximale °C')),
                ('besoin_eau_min', models.FloatField(help_text='Besoin en eau minimum mm/cycle')),
                ('besoin_eau_max', models.FloatField(help_text='Besoin en eau maximum mm/cycle')),
                ('tolerance_secheresse', models.IntegerField(choices=[(1, 'Faible'), (2, 'Moyenne'), (3, 'Élevée')], default=2)),
                ('tolerance_exces_eau', models.IntegerField(choices=[(1, 'Faible'), (2, 'Moyenne'), (3, 'Élevée')], default=2)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('source_url', models.URLField(blank=True)),
                ('niveau_confiance', models.CharField(choices=[('faible', 'Faible'), ('moyen', 'Moyen'), ('eleve', 'Élevé')], default='moyen', max_length=20)),
                ('date_verification', models.DateField(blank=True, null=True)),
                ('culture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_climatique', to='cultures.culture')),
            ],
        ),
        migrations.CreateModel(
            name='Variete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('duree_min', models.PositiveIntegerField(help_text='Durée minimale en jours')),
                ('duree_max', models.PositiveIntegerField(help_text='Durée maximale en jours')),
                ('description', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varietes', to='cultures.culture')),
            ],
            options={
                'verbose_name': 'Variété',
                'verbose_name_plural': 'Variétés',
                'ordering': ['nom'],
                'unique_together': {('culture', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='EtapeCulturelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('type_etape', models.CharField(choices=[('preparation', 'Préparation'), ('semis', 'Semis'), ('entretien', 'Entretien'), ('fertilisation', 'Fertilisation'), ('traitement', 'Traitement'), ('surveillance', 'Surveillance'), ('recolte', 'Récolte')], max_length=30)),
                ('decalage_min', models.IntegerField(help_text='Décalage minimum en jours (peut être négatif)')),
                ('decalage_max', models.IntegerField(help_text='Décalage maximum en jours (peut être négatif)')),
                ('description', models.TextField(blank=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('obligatoire', models.BooleanField(default=True)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='cultures.culture')),
            ],
            options={
                'verbose_name': 'Étape culturelle',
                'verbose_name_plural': 'Étapes culturales',
                'ordering': ['ordre', 'decalage_min'],
                'unique_together': {('culture', 'ordre')},
            },
        ),
        migrations.CreateModel(
            name='CalendrierZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saison', models.CharField(choices=[('A', 'Saison A'), ('B', 'Saison B')], max_length=1)),
                ('semis_debut_jour', models.IntegerField(help_text="Jour de l'année (1-365)")),
                ('semis_fin_jour', models.IntegerField(help_text="Jour de l'année (1-365)")),
                ('recolte_debut_jour', models.IntegerField(help_text="Jour de l'année (1-365)")),
                ('recolte_fin_jour', models.IntegerField(help_text="Jour de l'année (1-365)")),
                ('source', models.CharField(blank=True, max_length=255)),
                ('niveau_confiance', models.CharField(choices=[('faible', 'Faible'), ('moyen', 'Moyen'), ('eleve', 'Élevé')], default='moyen', max_length=20)),
                ('actif', models.BooleanField(default=True)),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendriers_zone', to='cultures.culture')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendriers', to='cultures.zoneagricole')),
            ],
            options={
                'verbose_name': 'Calendrier par zone',
                'verbose_name_plural': 'Calendriers par zone',
                'ordering': ['culture__nom', 'zone__province'],
                'unique_together': {('culture', 'zone', 'saison')},
            },
        ),
    ]
