# Generated by Django 4.2.7 on 2026-08-19 10:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cultures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilSaison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: Saison agricole 2026-2027', max_length=100)),
                ('saison', models.CharField(choices=[('A', 'Saison A'), ('B', 'Saison B')], max_length=1)),
                ('pluie_tendance', models.CharField(choices=[('au_dessus', 'Au-dessus de la normale'), ('normal', 'Normal'), ('en_dessous', 'En dessous de la normale')], max_length=20)),
                ('temperature_tendance', models.CharField(choices=[('au_dessus', 'Au-dessus de la normale'), ('normal', 'Normal'), ('en_dessous', 'En dessous de la normale')], max_length=20)),
                ('vent_tendance', models.CharField(choices=[('au_dessus', 'Au-dessus de la normale'), ('normal', 'Normal'), ('en_dessous', 'En dessous de la normale')], max_length=20)),
                ('pluie_probabilite', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('debut_pluies_debut', models.DateField(blank=True, null=True)),
                ('debut_pluies_fin', models.DateField(blank=True, null=True)),
                ('niveau_confiance', models.CharField(choices=[('faible', 'Faible'), ('moyen', 'Moyen'), ('eleve', 'Élevé')], default='moyen', max_length=20)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profils_saison', to='cultures.zoneagricole')),
            ],
            options={
                'verbose_name': 'Profil de saison',
                'verbose_name_plural': 'Profils de saison',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='RecommandationSaison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('periode_semis_conseillee', models.CharField(blank=True, max_length=200)),
                ('varietes_conseillees', models.TextField(blank=True)),
                ('precautions', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultures.culture')),
                ('profil_saison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommandations', to='saisons.profilsaison')),
            ],
            options={
                'verbose_name': 'Recommandation de saison',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ScoreCultureSaison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_pluie', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('score_temperature', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('score_global', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('niveau', models.CharField(choices=[('favorable', '🟢 Favorable'), ('attention', '🟡 Avec précautions'), ('defavorable', '🔴 Défavorable')], max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores_saison', to='cultures.culture')),
                ('profil_saison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores_cultures', to='saisons.profilsaison')),
            ],
            options={
                'verbose_name': 'Score culture-saison',
                'ordering': ['-score_global'],
                'unique_together': {('profil_saison', 'culture')},
            },
        ),
    ]
