# Generated by Django 4.2.7 on 2026-08-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saisons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilsaison',
            name='source',
            field=models.CharField(blank=True, help_text='Source des données météo', max_length=255),
        ),
    ]
