# Generated by Django 4.2.7 on 2026-08-19 10:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parcelles', '0001_initial'),
        ('cultures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_prevue', models.DateField()),
                ('date_originale', models.DateField(default=django.utils.timezone.now, help_text='Date initiale sans ajustement')),
                ('date_realisation', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('a_venir', 'À venir'), ('realise', 'Réalisé'), ('en_retard', 'En retard'), ('annule', 'Annulé'), ('reporte', 'Reporté')], default='a_venir', max_length=20)),
                ('report_count', models.IntegerField(default=0, help_text="Nombre de fois que l'étape a été reportée")),
                ('raison_report', models.TextField(blank=True, help_text='Raison du report')),
                ('est_ajustee', models.BooleanField(default=False, help_text='La date a-t-elle été ajustée ?')),
                ('date_ajustement', models.DateTimeField(blank=True, help_text='Date du dernier ajustement', null=True)),
                ('etape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultures.etapeculturelle')),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendrier', to='parcelles.parcelle')),
            ],
            options={
                'verbose_name': 'Calendrier',
                'verbose_name_plural': 'Calendriers',
                'ordering': ['date_prevue'],
                'unique_together': {('parcelle', 'etape')},
            },
        ),
    ]
