# Generated by Django 4.2.7 on 2026-08-19 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cultures', '0001_initial'),
        ('parcelles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteParcelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('observation', 'Observation'), ('maladie', 'Maladie'), ('ravageur', 'Ravageur'), ('recolte', 'Récolte'), ('irrigation', 'Irrigation'), ('engrais', 'Engrais'), ('autre', 'Autre')], default='observation', max_length=20)),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='notes/%Y/%m/%d/')),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_parcelles', to=settings.AUTH_USER_MODEL)),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='parcelles.parcelle')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ActionRealisee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_realisation', models.DateField(auto_now_add=True)),
                ('commentaire', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, help_text="GPS lors de l'action", max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, help_text="GPS lors de l'action", max_digits=10, null=True)),
                ('etape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultures.etapeculturelle')),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions_realisees', to='parcelles.parcelle')),
                ('realise_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_realisees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Action réalisée',
                'verbose_name_plural': 'Actions réalisées',
                'ordering': ['-date_realisation'],
            },
        ),
    ]
