# Generated by Django 4.2.7 on 2026-08-19 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parcelles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='analyses/%Y/%m/%d/')),
                ('resultat', models.JSONField(default=dict)),
                ('score_sante', models.IntegerField(default=0, help_text='Score de santé 0-100')),
                ('niveau_risque', models.CharField(default='inconnu', max_length=20)),
                ('conseils', models.TextField(blank=True)),
                ('modele_utilise', models.CharField(default='gemini-2.0-flash', max_length=50)),
                ('temps_execution', models.FloatField(default=0, help_text="Temps d'exécution en secondes")),
                ('date_analyse', models.DateTimeField(auto_now_add=True)),
                ('meteo_contexte', models.JSONField(blank=True, default=dict)),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses_images', to='parcelles.parcelle')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses_ia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Analyse d'image",
                'verbose_name_plural': "Analyses d'images",
                'ordering': ['-date_analyse'],
            },
        ),
    ]
